#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width                2
bspc config window_gap                  8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# RULES

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a nautilus state=floating
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

#AutoStart
xrdb .Xresources
picom -b
#xwallpaper --zoom ~/Pictures/wallpapers/showerr.jpg
$HOME/.config/polybar/launch.sh
dunst &
